# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with pylint
      run: |
        score=$(pylint $(git ls-files '*.py') | tee /dev/tty | grep -o "rated at [0-9.]*" | awk '{print $3}')
        if (( $(echo "$score < 0.9" | bc -l) )); then
          echo "::error file=pylint::Pylint score is below 0.9: $score"
        exit 1
        elif (( $(echo "$score < 1.0" | bc -l) )); then
          echo "::warning file=pylint::Pylint score is below 1.0: $score"
        fi
    - name: Test with pytest
      run: |
        pytest --cov=src --cov-report=xml tests/
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
